-- Per-user-message metadata for the "📎 attach current note" toggle in
-- the AI panel. When the user sends a message with the note attached,
-- the client composes the final user-content string (text + the note
-- body in an <attached_note> block, truncated at 20K codepoints if
-- needed) and we persist both:
--   - the composed string in `content` (the model sees it as-is), and
--   - the metadata in `note_attachment` (JSON: {path, truncated,
--     originalCodepoints, attachedCodepoints}) so the UI can render a
--     truncation banner on reload.
--
-- NULL for old rows and for messages sent without the toggle on. Only
-- user rows can carry it (CHECK role='user'), but the column is
-- nullable so we don't need a separate migration if we ever want to
-- attach context to assistant messages.
ALTER TABLE messages ADD COLUMN note_attachment TEXT;
